#!/bin/bash
# ##############################################################################
# Bestand:  _script
# Doel:     Functie voor tab-completion eigen scripts
# Gebruik:  Gesourced door _script_completion (aanbevolen)
#      of:  In het terminalvenster:
#           source _script SCRIPT
# Auteur:   Karel Zimmer (https://karelzimmer.nl, info@karelzimmer.nl)
#           Naar voorbeeld op het internet:
#               https://askubuntu.com/questions/68175
# ------------------------------------------------------------------------------
# Auteursrecht (c) 2017-2020 Karel Zimmer.
#
# Dit programma is vrije software: u mag het herdistribueren en/of wijzigen
# onder de voorwaarden van de GNU Algemene Publieke Licentie zoals gepubliceerd
# door de Free Software Foundation, onder versie 3 van de Licentie of (naar uw
# keuze) elke latere versie.
#
# Dit programma is gedistribueerd in de hoop dat het nuttig zal zijn maar ZONDER
# ENIGE GARANTIE; zelfs zonder de impliciete garanties die GEBRUIKELIJK ZIJN IN
# DE HANDEL of voor BRUIKBAARHEID VOOR EEN SPECIFIEK DOEL.
# Zie de GNU Algemene Publieke Licentie voor meer details.
#
# U hoort een kopie van de GNU Algemene Publieke Licentie te hebben ontvangen
# samen met dit programma. Als dat niet het geval is, zie
# http://www.gnu.org/licenses/.
# ##############################################################################
# REL_NUM=01.02.02
# REL_DAT=2019-12-07
# REL_MSG='Wijzig autersrechttekst'

# ##############################################################################
# Instellingen
# ##############################################################################
# declare i.v.m. source.
declare PROGNAME=_script
if [[ $1 == *-h* || $1 == *-u* ]]; then
    printf '%s\n' "Gebruik: source $PROGNAME [SCRIPT]"
    exit 0
fi

# ------------------------------------------------------------------------------
# Globale constanten
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Globale variabelen
# ------------------------------------------------------------------------------

# ##############################################################################
# Functies
# ##############################################################################

# ##############################################################################
# Hoofdlijn
# ##############################################################################
_script()
{
    script_opts="$("$1" --zz-tab-compl)"
    local cur
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    COMPREPLY=( $(compgen -W "$script_opts" -- "$cur") )
    return 0
}

complete -o default -F _script "$(basename "$1")"

# Einde script
