#!/bin/bash
#############################################################################
# Bestand:  ckinst                                                          #
# Doel:     Controleer informatieteksten in installatie- en instellings-    #
#           bestanden.                                                      #
# Gebruik:  In het terminalvenster:                                         #
#           ckinst [OPTIES] [ARGUMENTEN]                                    #
#           Gebruik optie --usage of --help voor meer informatie.           #
# Gebruikt: script-common.sh (algemene variabelen en functies)              #
#           install-*.sh     (installatiebestanden)                         #
#           setup-*.sh       (instellingsbestanden)                         #
# Auteur:   Karel Zimmer (http://karelzimmer.nl, info@karelzimmer.nl)       #
# ------------------------------------------------------------------------- #
# Auteursrecht © 2016 Karel Zimmer.                                         #
#                                                                           #
# Dit programma is vrije software: u mag het herdistribueren en/of wijzigen #
# onder de voorwaarden van de GNU Algemene Publieke Licentie zoals          #
# gepubliceerd door de Free Software Foundation, onder versie 3 van de      #
# Licentie of (naar uw keuze) elke latere versie.                           #
#                                                                           #
# Dit programma is gedistribueerd in de hoop dat het nuttig zal zijn maar   #
# ZONDER ENIGE GARANTIE; zelfs zonder de impliciete garanties die           #
# GEBRUIKELIJK ZIJN IN DE HANDEL of voor BRUIKBAARHEID VOOR EEN SPECIFIEK   #
# DOEL.  Zie de GNU Algemene Publieke Licentie voor meer details.           #
#                                                                           #
# U hoort een kopie van de GNU Algemene Publieke Licentie te hebben         #
# ontvangen samen met dit programma. Als dat niet het geval is, zie         #
# http://www.gnu.org/licenses/.                                             #
# ------------------------------------------------------------------------- #
# Versies:  1.0.0   2016-10-20  Eerste versie.                              #
#############################################################################
readonly VERSION_NUMBER=1.0.3
readonly RELEASE_DATE=2016-12-05


#############################################################################
# Instellingen                                                              #
#############################################################################

#---------------------------------------------------------------------------#
# Algemene instellingen                                                     #
# ------------------------------------------------------------------------- #
# Lees de algemene variabelen en functies in.                               #
#---------------------------------------------------------------------------#
source  "$(dirname "$0")"/script-common.sh &> /dev/null ||
    {
        echo 'Het algemeen scriptbestand (script-common.sh) is niet gevonden'
        echo "of bevat fouten.  Is 'wget karelzimmer.nl/s;. s' uitgevoerd?"
        echo 'Zie voor informatie http://karelzimmer.nl en klik op LEESMIJ.'
        exit 1
    }

#---------------------------------------------------------------------------#
# Globale constanten                                                        #
#---------------------------------------------------------------------------#
# Algemeen ==================================================================
readonly SCRIPT_NEEDS_SUDO=false        # Geen beheerdersrechten nodig
readonly FIRST_COPYRIGHTYEAR=2016       # Eerste auteursrechtjaar

# Specifiek =================================================================
                                        # Standaard zoekbestanden:
readonly FILE_1_DEFAULT=$PROGDIR/install-*.sh
readonly FILE_2_DEFAULT=$PROGDIR/setup-*.sh
readonly MAXLINELEN=100                 # Maximale regellengte

readonly OPT_NEEDS_ARG=false            # Geen optie met een verplicht argum.
readonly OPTS_HELP=$(cat << OPTS_HELP

         BESTAND             verwerk bestand BESTANDen
OPTS_HELP
)                                       # Extra hulp-opties
readonly OPTS_USAGE=$(cat << OPTS_USAGE

                [BESTAND...]
OPTS_USAGE
)                                       # Extra gebruiks-opties
readonly HELP=$(cat << HELP

$PROGNAME - controleer informatieteksten in installatie- en \
instellingsbestanden

$OPTS_HELP_SC$OPTS_HELP

Standaard, tenzij BESTANDen zijn opgegeven, worden de volgende bestanden \
verwerkt:
 1. Installatiebestanden:
        $FILE_1_DEFAULT
 2. Instellingsbestanden:
        $FILE_2_DEFAULT

De te verwerken bestanden:
- dienen te beginnen met 'install-' of 'setup-',
- bevatten commentaar- en opdrachtregels, waarbij:
  1. een commentaarregel die begint met:
        # of spatie - is commentaar,
        #1          - is voortgangstekst,
        #2          - is informatietekst.
  2. Een regel met informatieteksten eruit ziet als:
        #2
        #2 +----------------------------------------------------------------+
        #2 |           <programmanaam> - <programmabeschrijving>            |
        #2 +----------------------------------------------------------------+
        #2 | <handeling> [-- <plug-in> voor <programmanaam> - <programma-   |
        #2 |              beschrijving>]                                    |
        #2 | 1. <beschrijving>                                              |
        #2 |   [-item]                                                      |
        #2 +----------------------------------------------------------------+
     Hierbij is:
        #2 |    <A>    <programmanaam> - <programmabeschrijving>    <B>     |
        de kopregel.
  3. De kopregels worden gecontroleerd op gecentreerd zijn van
        '  <A>  <programmanaam> - <programmabeschrijving>  <B>  ',
     meer precies:
        - A=B
        - A+1=B
        - rest wordt gerapporteerd
  4. De selectie hiervoor is:
        - regel begint met '#2 |'
        - regel bevat ' - ' (de kopregel)
        - regel bevat niet ' -- ' (eventuele informatie die ook ' - ' bevat)
HELP
)                                       # Hulptekst

# Foutcodes =================================================================

#---------------------------------------------------------------------------#
# Globale variabelen                                                        #
#---------------------------------------------------------------------------#
# Array, integer ============================================================
declare -a FILE_ARG                     # Opgegeven install./instell.bestand
declare -a FILE                         # Gebruikte install./instell.bestand

# Boolean ===================================================================
declare ARG_FILE=false                  # Install./instell.bestand opgegeven
declare OPT_LIST=false                  # Optie list opgegeven
declare FOUND=false                     # Controle uitgevoerd
declare NO_FILES_FOUND=true             # Geen bestanden gevonden

# Overig ====================================================================
declare FILLER=''                       # Opvulling


#############################################################################
# Functies                                                                  #
#############################################################################


#-Functie-------------------------------------------------------------------#
# Naam: controleer_invoer                                                   #
# Doel: Initiële controles en/of acties.                                    #
# Arg.: Geen argumenten.                                                    #
#---------------------------------------------------------------------------#
function controleer_invoer {
    log "$PROGNAME:$FUNCNAME:$LINENO"

    #-----------------------------------------------------------------------#
    # Verwerk optie list.                                                   #
    #-----------------------------------------------------------------------#
    if $OPT_LIST; then
        toon_bestanden
        exit 0
    fi

    #-----------------------------------------------------------------------#
    # Verwerk argument bestand.                                             #
    #-----------------------------------------------------------------------#
    if $ARG_FILE; then
        for file in "${!FILE_ARG[@]}"; do
            FILE[$file]="${FILE_ARG[$file]}"
        done
    else
        local -i file=0
        for dflt_file in $(echo "$FILE_1_DEFAULT"); do
            FILE[$file]="$dflt_file"
            (( file = file + 1 ))
        done
        for dflt_file in $(echo "$FILE_2_DEFAULT"); do
            FILE[$file]="$dflt_file"
            (( file = file + 1 ))
        done
    fi

    return 0
}


#-Functie-------------------------------------------------------------------#
# Naam: toon_bestanden                                                      #
# Doel: Toon beschikbare bestanden.                                         #
# Arg.: Geen argumenten.                                                    #
#---------------------------------------------------------------------------#
function toon_bestanden {
    log "$PROGNAME:$FUNCNAME:$LINENO"

    info 'De volgende bestanden zijn beschikbaar:'
    ls  --format=single-column  \
        $PROGDIR/install-*.sh   \
        $PROGDIR/setup-*.sh
    info
    info 'Deze bestanden zijn te gebruiken als invoer voor dit script:'
    info "$PROGNAME BESTAND..."

    return 0
}


#-Functie-------------------------------------------------------------------#
# Naam: toon_invoer                                                         #
# Doel: Toon wat het script gaat doen.                                      #
# Arg.: Geen argumenten.                                                    #
#---------------------------------------------------------------------------#
function toon_invoer {
    log "$PROGNAME:$FUNCNAME:$LINENO"

    info "    Script: $PROGNAME"
    info "Controleer: ${FILE[@]}" 
    info

    return 0
}


#-Functie-------------------------------------------------------------------#
# Naam: verwerk_invoer                                                      #
# Doel: Verwerk installatie- en instellingsbestanden.                       #
# Arg.: Geen argumenten.                                                    #
#---------------------------------------------------------------------------#
function verwerk_invoer {
    log "$PROGNAME:$FUNCNAME:$LINENO"

    info

    for file in "${FILE[@]}"; do

        #-------------------------------------------------------------------#
        # Controleer aanwezigheid bestand.                                  #
        #-------------------------------------------------------------------#
        [[ ! -f $file ]] &&
            {
                info "Bestand niet gevonden, sla over: $file"
                continue
            }

        #-------------------------------------------------------------------#
        # Controleer begin bestandsnaam.                                    #
        #-------------------------------------------------------------------#
        if [[ $(basename "$file") != install-* ]] &&
           [[ $(basename "$file") != setup-* ]]; then
            warning "Bestand moet beginnen met install- of setup-, sla \
over: $file"
            continue
        fi

        #-------------------------------------------------------------------#
        # Selecteer bestand.                                                #
        #-------------------------------------------------------------------#
        info --bold "$file"
        if  grep    --regexp='^#2 |' "$file"    |
            grep    --regexp=' - '              |
            grep    --invert-match              \
                    --quiet                     \
                    --regexp=' -- '; then
            verwerk_bestand "$file"
        else
            info 'Bestand '"$file"' bevat geen kopteksten.'
        fi
    done

    return 0
}


#-Functie-------------------------------------------------------------------#
# Naam: verwerk_bestand                                                     #
# Doel: Controleer informatieteksten in het opgegeven bestand.              #
# Arg.: Eén verplicht argument:                                             #
#       1. bestandsnaam     string, invoer                                  #
# Vb. : verwerk_bestand "$file"                                             #
#---------------------------------------------------------------------------#
function verwerk_bestand {
    log "$PROGNAME:$FUNCNAME:$LINENO:$@"

    local file=${1:-/tmp}
    local recordtype=''

    while read "record"; do
        # Bepaal recordsoort.
        recordtype=${record:0:4}
        case $recordtype in
            '#2 |')
                if  echo    "$record"                   |
                    grep    --regexp=' - '              |
                    grep    --invert-match              \
                            --quiet                     \
                            --regexp=' -- '; then
                    verwerk_voortgangstekst "$record" "${#record}"
                fi
                continue
                ;;
            *)
                continue
                ;;
        esac
    done < "$file"

    $FOUND || info "Bestand '$file' is ok."

    return 0
}


#-Functie-------------------------------------------------------------------#
# Naam: verwerk_voortgangstekst                                             #
# Doel: Hernummer voortgangstekst.                                          #
# Arg.: Eén verplicht argument:                                             #
#       1. voortgangstekst        string, invoer                            #
#       2. voortgangstekstlenhte  integer, invoer                           #
# Vb. : verwerk_voortgangstekst "$record"                                   #
#---------------------------------------------------------------------------#
function verwerk_voortgangstekst {
    log "$PROGNAME:$FUNCNAME:$LINENO:$@"

    local record=${1:-unspecified-record}
    local reclen=${2:-unspecified-reclen}
#   local file is gedefinieerd in aanroepende functie
    local -a spaces
    local -i i=0
    local -i space=1
    local -i spacecount=1
    local prev_byte=''

    # i=4 want we beginnen na '#2 |', reclen-1 want we beginnen bij 0
    for (( i=4; i <= reclen-1; i++ ));do
        byte=${record:i:1}

        # Hierdoor tellen we 1 spatie te weinig, daarom begint teller bij 1.
        if [[ $prev_byte = ' ' && $byte = ' ' ]];then
            let spacecount++
        fi

        # Een breuk in het patroon.
        if [[ $byte != "$prev_byte" ]]; then
            if [[ $prev_byte = ' ' ]]; then
                # Teller bij 1, alleen >1 tellen we mee.
                if [[ $spacecount -gt 1 ]]; then
                    spaces[$space]=$spacecount
                    let space++
                fi
                # Teller reset op 1 i.v.m. eerste if.
                spacecount=1
            fi
        fi

        # Array begint op 1.
        prev_byte=$byte
    done

    sp_li=${spaces[1]}
    sp_re=${spaces[2]}

    if ! [[ $sp_li -eq $sp_re || $sp_li -eq $(( $sp_re - 1 )) ]]; then
        FOUND=true
        warning "Regel '${record:3}' heeft links $sp_li en rechts $sp_re \
spaties."
    fi

    return 0
}


#-Functie-------------------------------------------------------------------#
# Naam: toon_afsluiten                                                      #
# Doel: Afsluitende meldingen en/of acties.                                 #
# Arg.: Geen argumenten.                                                    #
#---------------------------------------------------------------------------#
function toon_afsluiten {
    log "$PROGNAME:$FUNCNAME:$LINENO"

    info
    if $FOUND; then
        warning 'Er zijn aanpassingen nodig.'
    else
        success 'Controle is uitgevoerd, geen aanpassingen nodig.'
    fi

    return 0
}


#############################################################################
# Hoofdlijn                                                                 #
#############################################################################

# init_script
{
    controleer_invoer_sc    "$@"
    controleer_gebruiker_sc $SCRIPT_NEEDS_SUDO "$@"
    controleer_invoer
    toon_invoer
}

# verwerk
{
    toon_gestart_sc
    verwerk_invoer
    toon_gestopt_sc
}

# afsl_script
{
    toon_afsluiten
    toon_afsluiten_sc
    exit 0
}

# Einde script.
