.\" # ##########################################################################
.\" # Bestand:  getstarted.1
.\" # Doel:     Man-pagina van script getstarted
.\" # Gebruik:  In het terminalvenster:
.\" #           man getstarted
.\" # Auteur:   Karel Zimmer (https://karelzimmer.nl, info@karelzimmer.nl)
.\" # ##########################################################################
.\" Versiegegevens worden bijgehouden door deploy
.\" REL_NUM=20.03.01
.\" REL_DAT=2020-01-02
.\" REL_MSG='Variabele snap_loc toegeveogd aan check_aptd()'
.\"
.TH getstarted "1" "2020-01-02" "20.03.01" "getstarted"

.SH NAAM
getstarted \- Installeer scriptspakket en richt ontwikkelomgeving in

.SH SAMENVATTING
.B getstarted
[OPTIE...]

.SH BESCHRIJVING
\fBgetstarted\fR downloadt het scriptspakket en installeert deze.
Als ontwikkelaar op een niet-ontwikkelmachine wordt een ontwikkelomgeving
ingericht.

Het gebruik hangt af of het scriptspakket is geïnstalleerd.

In het terminalvenster:
.br
\fBwget -O- karelzimmer.nl/s|bash\fR


of, als curl is geïnstalleerd:
.br
\fBcurl -L karelzimmer.nl/s|bash\fR

of, oude methode:
.br
\fBwget karelzimmer.nl/s;bash s\fR

of, als scriptspakket is geïnstalleerd:
.br
\fBgetstarted\fR

N.B. /s mag vervangen worden door /getstarted (/s -> /getstarted).

Ook de website lokaal? Voer dan uit:
.br
\fBmkdir --parents ~/uploads/karelzimmer.nl/httpdocs
.br
lftp --user <USER> --password <PASSWORD> <HOST> -e \
'set ssl:verify-certificate no; mirror --delete /httpdocs \
~/uploads/karelzimmer.nl/httpdocs; exit'\fR

Een enkel bestand uploaden? Voer dan uit:
.br
\fBlftp --user <USER> --password <PASSWORD> <HOST> -e \
'set ssl:verify-certificate no; put -O \
/httpdocs/<DIR> $HOME/uploads/karelzimmer.nl/httpdocs/<DIR>/<FILE>; exit'\fR

.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1. Als er een waarschuwing optreedt, is de afsluitwaarde 2.

.SH AUTEUR
Geschreven door Karel Zimmer, https://karelzimmer.nl, info@karelzimmer.nl.

.SH AUTEURSRECHT
Auteursrecht (c) 2016-2020 Karel Zimmer.
.br
Dit is vrije software: u mag het vrijelijk wijzigen en verder verspreiden.
.br
De precieze licentie is GPL-3+: GNU General Public License versie 3 of later.
.br
Zie http://gnu.org/licenses/gpl.html voor de volledige (Engelse) tekst.
.br
Deze software kent GEEN GARANTIE, voor zover de wet dit toestaat.


.SH ZIE OOK
\fBhttps://karelzimmer.nl\fR
