#!/bin/bash

function create_development_environment {
    local ftp_set='set ssl:verify-certificate no'
    local ftp_from=/httpdocs
    local ftp_to=$HOME/uploads/karelzimmer.nl/httpdocs
    local ftp_opts='--delete --verbose'
    local ftp_cmd="mirror $ftp_opts $ftp_from $ftp_to; exit"
    local ftp_host=server106.hosting2go.nl
    local ftp_user=kzimmer
    local ftp_login=$HOME/.kz-$ftp_host
    local site_tar=https://karelzimmer.nl/apps/kzscripts/kzscripts.tar.gz
    local temp_tar=''
    local uploads=$HOME/uploads
    local uploads_old=$HOME/uploads.old

    # Pull website.
    if ! [[ -f $ftp_login ]]; then
        echo 'Vraag ww'
#        read -rsp "FTP-wachtwoord voor $ftp_host: " # werkt niet als cat | bash, FD 1 reeds in gebruik door deze constructie
        read -rsp "FTP-wachtwoord voor $ftp_host: " < /dev/tty
        printf '%s\n' "$REPLY" > "$ftp_login"
        printf '\n'
        chmod 'u=rw,g=,o=' "$ftp_login" |& $LOGCMD
    else
        echo 'Vraag niet ww'
    fi
}

create_development_environment
