#!/bin/bash
# shellcheck source=common.sh
# ##############################################################################
# Bestand:  lsinstal
# Doel:     Verzamel toegevoegde pakketbronnen en geïnstalleerde pakketten
# Gebruik:  Met starter 'Start Hier', kies 'Menu Opdrachten' (aanbevolen)
#      of:  In het terminalvenster:
#           lsinstal
# Auteur:   Karel Zimmer (https://karelzimmer.nl, info@karelzimmer.nl)
# ------------------------------------------------------------------------------
# Auteursrecht (c) 2013-2020 Karel Zimmer.
#
# Dit programma is vrije software: u mag het herdistribueren en/of wijzigen
# onder de voorwaarden van de GNU Algemene Publieke Licentie zoals gepubliceerd
# door de Free Software Foundation, onder versie 3 van de Licentie of (naar uw
# keuze) elke latere versie.
#
# Dit programma is gedistribueerd in de hoop dat het nuttig zal zijn maar ZONDER
# ENIGE GARANTIE; zelfs zonder de impliciete garanties die GEBRUIKELIJK ZIJN IN
# DE HANDEL of voor BRUIKBAARHEID VOOR EEN SPECIFIEK DOEL.
# Zie de GNU Algemene Publieke Licentie voor meer details.
#
# U hoort een kopie van de GNU Algemene Publieke Licentie te hebben ontvangen
# samen met dit programma. Als dat niet het geval is, zie
# http://www.gnu.org/licenses/.
# ##############################################################################
readonly REL_NUM=17.02.13
readonly REL_DAT=2019-12-11
readonly REL_MSG='Beschrijving opties aangepast'

# ##############################################################################
# Instellingen
# ##############################################################################
source "$(dirname "$0")"/common.sh

# ------------------------------------------------------------------------------
# Globale constanten
# ------------------------------------------------------------------------------
readonly OUTPUTFILE_1=/root/.$PROGNAME-$HOSTNAME-deb-bestanden
readonly OUTPUTFILE_2=/root/.$PROGNAME-$HOSTNAME-pakketbronnen
readonly OUTPUTFILE_3=/root/.$PROGNAME-$HOSTNAME-pakketten
readonly OUTPUTFILE_4=/root/.$PROGNAME-$HOSTNAME-favorieten
readonly OUTPUTFILE_5=/root/.$PROGNAME-$HOSTNAME-snaps
readonly RUN_AS_SUPERUSER=true

readonly OPTIONS_SHORT=$OPTIONS_SHORT_COMMON
readonly OPTIONS_LONG=$OPTIONS_LONG_COMMON
readonly OPTIONS_TAB_COMPLETION=$OPTIONS_TAB_COMPLETION_COMMON
readonly USAGE="Gebruik: $PROGNAME
                  $OPTIONS_USAGE_COMMON

$OPTIONS_LONG_SHORT"
readonly HELP="Gebruik: $PROGNAME [OPTIE...]

Verzamel toegevoegde pakketbronnen en geïnstalleerde pakketten.

Opties:
  $OPTIONS_LONG_SHORT

$OPTIONS_HELP_COMMON"

# ------------------------------------------------------------------------------
# Globale variabelen
# ------------------------------------------------------------------------------

# ##############################################################################
# Functies
# ##############################################################################
controleer_invoer() {
    local -i getopt_rc=0
    local parsed=''

    set +o errexit
    parsed=$(getopt --alternative                       \
                    --options       "$OPTIONS_SHORT"    \
                    --longoptions   "$OPTIONS_LONG"     \
                    --name          "$PROGNAME"         \
                    -- "$@")
    getopt_rc=$?
    set -o errexit
    if [[ $getopt_rc -ne 0 ]]; then
        printf '%s\n' "$HELPLINE" >&2
        quiet; exit $ERROR
    fi
    eval set -- "$parsed"
    verwerk_algemene_opties "$@"

    while true; do
        case $1 in
            --)
                shift
                break
                ;;
            *)
                shift
                ;;
        esac
    done

    if [[ "$*" ]]; then
        printf '%s\n%s\n' "Geen argumenten opgeven." "$HELPLINE" >&2
        quiet; exit $ERROR
    fi

    controleer_gebruiker
}

verwerk_invoer() {
    local title="$PROGNAME"
    local text0='Opdrachten worden verwerkt...'
    local text1="[1/5]  Bepaal welke deb-bestanden (Debian-pakketten) zijn \
geïnstalleerd..."
    local text2="[2/5]  Bepaal welke pakketbronnen (\"repositories\" of \
\"repo's\") zijn toegevoegd..."
    local text3="[3/5]  Bepaal welke pakketten door de gebruiker zijn \
geïnstalleerd..."
    local text4='[4/5]  Bepaal welke favorieten in gebruik zijn...'
    local text5='[5/5]  Bepaal welke snaps zijn geïnstalleerd...'
    local wait_for_zenity_progress=1s

    rm --force "$HOME"/."$PROGNAME"*"$HOSTNAME"*

    if $OPTION_GUI; then
        (
        printf '%s\n' "#$text1"; sleep $wait_for_zenity_progress
        maak_bestand_zonder_repo_geinstalleerd      #1
        printf '%s\n' "#$text2"; sleep $wait_for_zenity_progress
        maak_bestand_toegevoegde_repos              #2
        printf '%s\n' "#$text3"; sleep $wait_for_zenity_progress
        maak_bestand_door_gebruiker_geinstalleerd   #3
        printf '%s\n' "#$text4"; sleep $wait_for_zenity_progress
        maak_bestand_favorieten                     #4
        printf '%s\n' "#$text5"; sleep $wait_for_zenity_progress
        maak_bestand_snaps                          #5
        ) |&
        zenity  --progress          \
                --pulsate           \
                --auto-close        \
                --no-cancel         \
                --width=600         \
                --height=50         \
                --title="$title"    \
                --text="$text0"     \
                2> /dev/null
    else
        maak_bestand_zonder_repo_geinstalleerd      #1
        maak_bestand_toegevoegde_repos              #2
        maak_bestand_door_gebruiker_geinstalleerd   #3
        maak_bestand_favorieten                     #4
        maak_bestand_snaps                          #5
    fi
}

#1
maak_bestand_zonder_repo_geinstalleerd() {
    local number_of_lines=0
    local header="Dit zijn gedownloade deb-bestanden geïnstalleerd via \
Software, of met een opdracht zoals 'sudo apt-get --install <bestand.deb>'."
    local footer=''

    printf '%s\n' "$text1"

    touch   "$OUTPUTFILE_1" |& $LOGCMD

    echo -e "$header\n$DASHES" > "$OUTPUTFILE_1"

    apt-show-versions --initialize          |& $LOGCMD
    if !    apt-show-versions                       |
            grep    --regexp='No available version' |
            cut     --delimiter=':'                 \
                    --fields=1                      >> "$OUTPUTFILE_1"; then
        true
    fi

    number_of_lines=$(wc --lines < "$OUTPUTFILE_1")
    number_of_lines=$(( number_of_lines - 2 ))
    footer="Dit bestand bevat $number_of_lines door de gebruiker \
geïnstalleerde deb-bestanden.
Meer echo via de opdracht: apt-cache show <bestand> | grep \
--regexp='Description:'"
    echo -e "$DASHES\n$footer" >> "$OUTPUTFILE_1"
}

#2
maak_bestand_toegevoegde_repos() {
    local number_of_lines=0
    local header="Deze pakketbronnen zijn meestal toegevoegd met de opdracht \
'sudo add-apt-repository ppa:<ppa-gebruiker>/<ppa-naam>'."
    local footer=''

    printf '%s\n' "$text2"

    touch   "$OUTPUTFILE_2" |& $LOGCMD

    echo -e "$header\n$DASHES" > "$OUTPUTFILE_2"

    # shellcheck disable=SC2022,SC2062
    if !    grep    --recursive             \
                    --no-filename           \
                    --regexp='^deb '        \
                    /etc/apt/sources.list*  |
            grep    --invert-match          \
                    --regexp='ubuntu.com'   |
            sort    --unique                >> "$OUTPUTFILE_2"; then
        true
    fi

    number_of_lines=$(wc --lines < "$OUTPUTFILE_2")
    number_of_lines=$(( number_of_lines - 2 ))
    footer="Dit bestand bevat $number_of_lines door de gebruiker toegevoegde \
pakketbronnen."
    echo -e "$DASHES\n$footer" >> "$OUTPUTFILE_2"
}

#3
maak_bestand_door_gebruiker_geinstalleerd() {
    local number_of_lines=0
    local header="Deze pakketten zijn meestal geïnstalleerd met Software of \
met de opdracht 'sudo apt install <pakketnaam>'."
    local footer=''

    printf '%s\n' "$text3"

    touch   "$OUTPUTFILE_3" |& $LOGCMD

    echo -e "$header\n$DASHES" > "$OUTPUTFILE_3"

    # Ref:
    # http://superuser.com/questions/48374/find-all-user-installed-packages
    # Tabel1 = Alle geïnstalleerde pakketten tijdens de installatie
    #           (gzip --decompress --to-stdout ...)
    # Tabel2 = Alle geïnstalleerde pakketten op dit moment
    #           (dpkg-query --show --showformat='${Package}\n' | sort)
    # Tabel3 = Alle *automatisch* geïnstalleerde pakketten op dit moment
    #           (apt-mark showauto | sort)
    # Tabel4 = Potentieel door gebruiker geïnstalleerd (Tabel2-Tabel3)
    #           (comm -23 Tabel2 Tabel3)
    # Tabel5 = Door gebruiker geïnstalleerd (Tabel4-Tabel1)
    #           (comm -13 Tabel1 Tabel4)
    comm -13    <(
        gzip    --decompress                            \
                --to-stdout                             \
                /var/log/installer/initial-status.gz    |
        sed     --quiet --expression='s/^Package: //p'  |
        sort
        )                                               \
        <(
            comm    -23                                 \
            <(
                dpkg-query  --show                      \
                            --showformat='${Package}\n' |
                sort
                )                                       \
            <(
                apt-mark    showauto                    |
                sort
                )                                       \
            )                                           >> "$OUTPUTFILE_3"
    number_of_lines=$(wc --lines < "$OUTPUTFILE_3")
    number_of_lines=$(( number_of_lines - 2 ))
    footer="Dit bestand bevat $number_of_lines door de gebruiker \
geïnstalleerde pakketten.
Meer info via de opdracht: apt-cache show <pakketnaam> | grep \
--regexp='Description:'"
    echo -e "$DASHES\n$footer" >> "$OUTPUTFILE_3"
}

#4
maak_bestand_favorieten() {
    local number_of_lines=0
    local header="Deze favorieten zijn de snelkoppelingen te bereiken via een \
(soort van) (snel)menu."
    local footer=''

    printf '%s\n' "$text4"

    touch   "$OUTPUTFILE_4" |& $LOGCMD

    echo -e "$header\n$DASHES" > "$OUTPUTFILE_4"

    if gsettings get org.gnome.shell favorite-apps &> /dev/null; then
        favorites=$(gsettings get org.gnome.shell favorite-apps)
    else
        echo "           Niet op GNOME (e.g. Ubuntu). Geen favorieten \
veiliggesteld." >> "$OUTPUTFILE_4"
        favorites=''
    fi
    favorites=${favorites//,/}
    favorites=${favorites//.desktop/}
    favorites=${favorites//\[/}
    favorites=${favorites//\]/}
    for favorite in $favorites; do
        echo "${favorite//"'"/}" >> "$OUTPUTFILE_4"
    done
    number_of_lines=$(wc --lines < "$OUTPUTFILE_4")
    number_of_lines=$(( number_of_lines - 2 ))
    footer="Dit bestand bevat $number_of_lines favorieten."
    echo -e "$DASHES\n$footer" >> "$OUTPUTFILE_4"
}

#5
maak_bestand_snaps() {
    local number_of_lines=0
    local header="Deze snaps zijn geïnstalleerd met '[sudo] install SNAP' of \
met Software."
    local footer=''

    printf '%s\n' "$text5"

    touch   "$OUTPUTFILE_5" |& $LOGCMD

    echo -e "$header\n$DASHES" > "$OUTPUTFILE_5"

    if ! snap list 2> /dev/null >> "$OUTPUTFILE_5"; then
        echo 'snap is niet geïnstalleerd op dit systeem' >> "$OUTPUTFILE_5"
    fi
    number_of_lines=$(wc --lines < "$OUTPUTFILE_5")
    number_of_lines=$(( number_of_lines - 3 ))
    footer="Dit bestand bevat $number_of_lines snaps."
    echo -e "$DASHES\n$footer" >> "$OUTPUTFILE_5"
}

term_script() {
    toon_tekst "
De vijf aangemaakte VERBORGEN bestanden (.$PROGNAME-*.list) staan in de \
Persoonlijke map van de superuser (/root).
Deze bestanden kunnen gebruikt worden om de volledigheid van de installatie,
later door instal, te controleren."
    quiet; exit $SUCCESS
}

verwerk_script() {
    controleer_invoer "$@"
    verwerk_invoer
}

# ##############################################################################
# Hoofdlijn
# ##############################################################################
main() {
    init_script
    verwerk_script "$@"
    term_script
}

main "$@"

# Einde script
