#!/bin/bash
# shellcheck source=common.sh
# ##############################################################################
# Bestand:  restore
# Doel:     Zet bestanden en mappen terug uit een back-up (reservekopie)
# Gebruik:  Met starter 'Start Hier', kies 'Menu Opdrachten' (aanbevolen)
#      of:  In het terminalvenster:
#           restore
# Auteur:   Karel Zimmer (https://karelzimmer.nl, info@karelzimmer.nl)
# ------------------------------------------------------------------------------
# Auteursrecht (c) 2007-2020 Karel Zimmer.
#
# Dit programma is vrije software: u mag het herdistribueren en/of wijzigen
# onder de voorwaarden van de GNU Algemene Publieke Licentie zoals gepubliceerd
# door de Free Software Foundation, onder versie 3 van de Licentie of (naar uw
# keuze) elke latere versie.
#
# Dit programma is gedistribueerd in de hoop dat het nuttig zal zijn maar ZONDER
# ENIGE GARANTIE; zelfs zonder de impliciete garanties die GEBRUIKELIJK ZIJN IN
# DE HANDEL of voor BRUIKBAARHEID VOOR EEN SPECIFIEK DOEL.
# Zie de GNU Algemene Publieke Licentie voor meer details.
#
# U hoort een kopie van de GNU Algemene Publieke Licentie te hebben ontvangen
# samen met dit programma. Als dat niet het geval is, zie
# http://www.gnu.org/licenses/.
# ##############################################################################
readonly REL_NUM=36.01.16
readonly REL_DAT=2019-12-11
readonly REL_MSG='Beschrijving opties aangepast'

# ##############################################################################
# Instellingen
# ##############################################################################
source "$(dirname "$0")"/common.sh

# ------------------------------------------------------------------------------
# Globale constanten
# ------------------------------------------------------------------------------
declare -ir BUPNUMLEN=2
readonly EXCLUDEFILE_DEFAULT=/root/.$PROGNAME-exclude-dflt
readonly EXCLUDEFILE_DEFAULT_CONTENT="\
$(find /etc/skel -type f -exec basename '{}' \; | awk '$0="/home/*/"$0')"
# Hieboven worden de bestanden opgenomen die bij het aanmaken van een
# gebruiker worden neergezet in $HOME. Meestal zijn dit de bestanden
# .bash_logout, .bashrc, examples.desktop, en .profile (bij Ubuntu).
# Deze bestanden terugzetten bij een nieuwe versie van Linux betekent dat
# deze bestanden worden teruggezeten naar de oude versie; niet wenselijk.
readonly EXCLUDEFILE_OPTIONAL=/root/.$PROGNAME-exclude-opt
readonly SELECTION_DEFAULT=''
readonly RUN_AS_SUPERUSER=true
readonly SOURCE_DEFAULT=/media
readonly TARGET_DEFAULT=/

readonly OPTIONS_SHORT=$OPTIONS_SHORT_COMMON's:t:x:'
readonly OPTIONS_LONG=$OPTIONS_LONG_COMMON',source:,target:,exclude:'
readonly OPTIONS_TAB_COMPLETION=$OPTIONS_TAB_COMPLETION_COMMON" --source \
--target --exclude"
readonly USAGE="Gebruik: $PROGNAME [-s|--source=BRON] \
[-t|--target=DOEL] [-x|--exclude=UITSLUITEN]...
                 $OPTIONS_USAGE_COMMON
                 [SELECTIE...]

$OPTIONS_LONG_SHORT

$ARGUMENT_LONG_SHORT"
readonly HELP="Gebruik: $PROGNAME [OPTIE...] [--] [SELECTIE...]

Zet elk gegeven SELECTIE bestanden en mappen terug uit een back-up \
(reservekopie).

Opties:
  $OPTIONS_LONG_SHORT

  $ARGUMENT_LONG_SHORT

  -s --source=BRON    Zoek back-upbestand vanaf map BRON
  -t --target=DOEL    Zet back-up terug in map DOEL
  -x --exclude=UITSLUITEN
                      Sluit uit bestand of map in UITSLUITEN
$OPTIONS_HELP_COMMON

Argument:
  SELECTIE            Zet opgegeven mappen en bestanden terug"

# ------------------------------------------------------------------------------
# Globale variabelen
# ------------------------------------------------------------------------------
declare -a EXCLUDE_ARGUMENT=''
declare ARGUMENT_SELECTION=false
declare -a SELECTION=''
declare -a SELECTION_ARGUMENT=''
declare BACKUP=''
declare BACKUPSIZE_HUMAN=''
declare -i BACKUPSIZE_MACHINE=0
declare -i TAR_RC=0
declare OPTION_EXCLUDE=false
declare OPTION_SOURCE=false
declare OPTION_TARGET=false
declare SOURCE=''
declare SOURCE_ARGUMENT=''
declare TARGET=''
declare TARGET_ARGUMENT=''

# ##############################################################################
# Functies
# ##############################################################################
controleer_invoer() {
    local -i exclude_arg_num=0
    local -i getopt_rc=0
    local -i select_arg_num=0
    local -i select_num=0
    local parsed=''

    set +o errexit
    parsed=$(getopt --alternative                       \
                    --options       "$OPTIONS_SHORT"    \
                    --longoptions   "$OPTIONS_LONG"     \
                    --name          "$PROGNAME"         \
                    -- "$@")
    getopt_rc=$?
    set -o errexit
    if [[ $getopt_rc -ne 0 ]]; then
        printf '%s\n' "$HELPLINE" >&2
        quiet; exit $ERROR
    fi
    eval set -- "$parsed"
    verwerk_algemene_opties "$@"

    while true; do
        case $1 in
            -s|--source)
                if $OPTION_SOURCE; then
                    printf '%s\n%s\n' \
"Optie '$1' éénmaal opgeven." "$HELPLINE" >&2
                    quiet; exit $ERROR
                else
                    OPTION_SOURCE=true
                    SOURCE_ARGUMENT=$2
                fi
                shift 2
                ;;
            -t|--target)
                if $OPTION_TARGET; then
                    printf '%s\n%s\n' \
"Optie '$1' éénmaal opgeven." "$HELPLINE" >&2
                    quiet; exit $ERROR
                else
                    OPTION_TARGET=true
                    TARGET_ARGUMENT=$2
                fi
                shift 2
                ;;
            -x|--exclude)
                OPTION_EXCLUDE=true
                EXCLUDE_ARGUMENT[$exclude_arg_num]=$2
                (( ++exclude_arg_num ))
                shift 2
                ;;
            --)
                shift
                break
                ;;
            *)
                shift
                ;;
        esac
    done

    while [[ "$*" ]]; do
        ARGUMENT_SELECTION=true
        SELECTION_ARGUMENT[$select_arg_num]=$1
        (( ++select_arg_num ))
        shift
    done

    if $OPTION_SOURCE; then
        SOURCE=$SOURCE_ARGUMENT
        if [[ ! -d $SOURCE ]]; then
            toon_tekst "Map '$SOURCE' bestaat niet."
            quiet; exit $ERROR
        fi
    else
        SOURCE=$SOURCE_DEFAULT
    fi

    if $OPTION_TARGET; then
        if [[ ! -d $TARGET_ARGUMENT ]]; then
            toon_tekst "Map '$TARGET_ARGUMENT' bestaat niet."
            quiet; exit $ERROR
        fi
        TARGET=$TARGET_ARGUMENT
    else
        TARGET=$TARGET_DEFAULT
    fi

    if $ARGUMENT_SELECTION; then
        for select_num in "${!SELECTION_ARGUMENT[@]}"; do
            if [[ ${SELECTION_ARGUMENT[$select_num]:0:1} = '/' ]]; then
                SELECTION[$select_num]=${SELECTION_ARGUMENT[$select_num]:1}
            else
                SELECTION[$select_num]=${SELECTION_ARGUMENT[$select_num]}
            fi
        done
    else
        SELECTION[0]=$SELECTION_DEFAULT
    fi

    controleer_gebruiker
    vraag_invoer
}

vraag_invoer() {
    local title="$PROGNAME"

    if $OPTION_GUI; then
        selecteer_backup_gui
    else
        selecteer_backup_tui
    fi
}

selecteer_backup_gui() {
    local title="$PROGNAME selecteer een back-upbestand"
    local filename="${SOURCE_ARGUMENT:-/media}"

    set +o errexit
    BACKUP="$(
        zenity  --file-selection        \
                --width=600             \
                --height=50             \
                --title="$title"        \
                --filename="$filename"  \
                --file-filter=*.tar     \
                2> /dev/null
        )"
    # shellcheck disable=SC2181
    if [[ $? -ne 0 ]]; then
        quiet; exit $WARNING
    fi
    set -o errexit
}

selecteer_backup_tui() {
    local range=''
    local -a buparray
    local -i bupnum=0

    toon_tekst "Er wordt naar back-ups gezocht vanaf '$SOURCE'.
Het medium waarop de back-up staat dient aangekoppeld te zijn.
Voorbeelden van een medium zijn een (externe) (netwerk)schijf,
USB-stick, CD, of DVD.
Zoek nu naar back-ups van deze computer..."

    toon_backups "$HOSTNAME"

    if [[ $bupnum -eq 0 ]]; then
        toon_waarschuwingstekst "Geen back-ups gevonden van deze computer \
($HOSTNAME)."
        REPLY='A'
    fi

    if [[ $bupnum -gt 0 ]]; then
        printf '\n%s\n' \
"Kies nummer, of A om te zoeken naar alle back-ups, en S om te stoppen."
        if [[ $bupnum -eq 1 ]]; then
            range=''
        else
            range="-$bupnum"
        fi
        while true; do
            read  -rp "Terugzetten back-up nummer (1$range, of A, of S, \
standaard 1): " </dev/tty
            case $REPLY in
                 '')
                    BACKUP=${buparray[1]}
                    break
                    ;;
                 a|A)
                    break
                    ;;
                 s|S)
                    printf '%s\n' 'Gestopt.'
                    quiet; exit $SUCCESS
                    ;;
                *[^[:digit:]]*)
                    echo -e "${UP_ONE_LINE}${ERASE_LINE}"
                    continue
                    ;;
                *)
                    if [[ $REPLY -ge 1 && $REPLY -le $bupnum ]] 2> /dev/null
                    then
                        BACKUP=${buparray[$REPLY]}
                        break
                    else
                        echo -e "${UP_ONE_LINE}${ERASE_LINE}"
                        continue
                    fi
                    ;;
            esac
        done
    fi

    if [[ $REPLY = [A,a] ]]; then
        printf '\n%s\n' "Zoek nu naar back-ups van alle computers..."
        bupnum=0
        toon_backups ''
        if [[ $bupnum -eq 0 ]]; then
            toon_waarschuwingstekst 'Geen back-ups gevonden.'
            quiet; exit $WARNING
        elif [[ $bupnum -eq 1 ]]; then
            range=''
        else
            range="-$bupnum"
        fi
        printf '\n%s\n' "Kies nummer, of S om te stoppen."
        while true; do
            read -rp "Terugzetten back-up nummer (1$range, of S, \
standaard S): " </dev/tty
            case $REPLY in
                 s|S|'')
                    printf '%s\n' 'Gestopt.'
                    quiet; exit $SUCCESS
                    ;;
                *[^[:digit:]]*)
                    echo -e "${UP_ONE_LINE}${ERASE_LINE}"
                    continue
                    ;;
                *)
                    if [[ $REPLY -ge 1 && $REPLY -le $bupnum ]] 2> /dev/null
                    then
                        BACKUP=${buparray[$REPLY]}
                        break
                    else
                        echo -e "${UP_ONE_LINE}${ERASE_LINE}"
                        continue
                    fi
                    ;;
            esac
        done
    fi
}

toon_backups() {
    local search4=${1-search4?}
    local backup=''
    local dirname=''
    local filename=''
    local filesize_human=''

    # Zoek vanaf bronmap ("$SOURCE") naar back-ups.  Find zoals hier gebruikt
    # levert, gescheiden door een TAB,  back-upnaam en directory waarin de
    # back-up zich bevindt.  De sort sorteert op back-upnaam aflopend, dat is
    # van nieuw naar oud.

    while read -r backup; do
        filename=$(echo "$backup" | cut --fields=1)
        dirname=$(echo  "$backup" | cut --fields=2)
        filesize_human=$(
            du  --apparent-size         \
                --block-size=1          \
                --human-readable        \
                "$dirname/$filename"    |
            awk '{print $1}'
            )

        (( ++bupnum ))
        buparray[$bupnum]=$dirname/$filename

        if [[ $bupnum -eq 1 ]]; then
            if [[ -z $search4 ]]; then
                printf '\n%s\n' "De volgende back-ups zijn gevonden:"
            else
                printf '\n%s\n' \
"De volgende back-ups van '$search4' zijn gevonden, van nieuw naar oud:"
            fi
        fi

        printf  '%+*s  %s\t%s\t%s\n'            \
                $BUPNUMLEN $bupnum              \
                "$(basename "$filename" .tar)"  \
                "$filesize_human"'iB' "$dirname"
    done < <(
        find    $SOURCE                             \
                -type f                             \
                -noleaf                             \
                -name 'backup*'"$search4"'*.tar'    \
                -printf '%f\t%h\n'                  \
                2> /dev/null                        |
        sort    --reverse
        )
}

verwerk_invoer() {
    local select=''
    local size_num=0
    local size_unit=''
    local text=''
    local title="$PROGNAME"

    echo  "$EXCLUDEFILE_DEFAULT_CONTENT" > "$EXCLUDEFILE_DEFAULT"

    if $OPTION_EXCLUDE; then
        for exclude in "${EXCLUDE_ARGUMENT[@]}"; do
            echo "$exclude" >> "$EXCLUDEFILE_OPTIONAL"
        done
    else
        cp /dev/null "$EXCLUDEFILE_OPTIONAL"
    fi

    text='Controleer beschikbare schijfruimte...'
    if $OPTION_GUI; then
        # Met "|& zenity --progress" worden globale variabelen uit
        # aangeroepen functies niet doorgegeven, vandaar de
        # 'process substitution' met "> >(zenity ...)".
        controleer_schijfruimte     > >(
        zenity  --progress          \
                --pulsate           \
                --auto-close        \
                --no-cancel         \
                --width=600         \
                --height=50         \
                --title="$title"    \
                --text="$text"      \
                2> /dev/null)
    else
        toon_tekst "$text"
        controleer_schijfruimte
    fi

    bepaal_bestandsgrootte

    if $ARGUMENT_SELECTION; then
        select='Selectie'
    else
        select='Alles'
    fi
    size_num=${BACKUPSIZE_HUMAN%?}
    size_unit=${BACKUPSIZE_HUMAN: -1}
    text=" uit back-up '$(basename "$BACKUP")' [$size_num ${size_unit}iB] \
wordt teruggezet"
    zet_backup_terug

    if [[ $TAR_RC -eq 0 ]]; then
        toon_tekst "$select uit back-up '$(basename "$BACKUP")' [$size_num \
${size_unit}iB] is teruggezet."
    fi
}

controleer_schijfruimte() {
    local filesys=''
    local free_human=''
    local -i free_bytes=0
    local -i need_bytes=0
    local mounted=''
    local need_human=''

    need_bytes=$(
        du  --apparent-size                         \
            --block-size=1                          \
            --exclude-from="$EXCLUDEFILE_DEFAULT"   \
            --exclude-from="$EXCLUDEFILE_OPTIONAL"  \
            --summarize                             \
            --total                                 \
            "$BACKUP"                               |
        awk 'END{print $1}'
        )
    free_bytes=$(df --block-size=1 "$TARGET" | awk 'END{print $4}')

    if [[ $need_bytes -gt $free_bytes ]]; then
        filesys=$(df "$TARGET" | awk 'END{print $1}')
        mounted=$(df "$TARGET" | awk 'END{print $6}')
        need_human=$(
            du  --apparent-size                         \
                --block-size=1                          \
                --exclude-from="$EXCLUDEFILE_DEFAULT"   \
                --exclude-from="$EXCLUDEFILE_OPTIONAL"  \
                --human-readable                        \
                --summarize                             \
                --total                                 \
                "$BACKUP"                               |
            awk 'END{print $1}'
            )
        free_human=$(df --human-readable "$TARGET" | awk 'END{print $4}')

        if [[ ${SELECTION[0]} = "$SELECTION_DEFAULT" ]]; then
            toon_fouttekst "Te weinig schijfruimte op $mounted \
(bestandssysteem $filesys)
voor het terugzetten van ALLES in $(basename "$BACKUP") naar $TARGET.
Overweeg het gebruik van optie SELECTIE.
$HELPLINE"
            quiet; exit $ERROR
        fi
        toon_waarschuwingstekst "Mogelijk te weinig schijfruimte (hangt af van \
de selectie)
op $mounted (bestandssysteem $filesys)
voor het terugzetten van ${SELECTION[*]} in $(basename "$BACKUP") naar \
$TARGET).
De HELE back-up is ${need_human}iB groot, beschikbaar is ${free_human}iB."
    fi
}

bepaal_bestandsgrootte() {
    BACKUPSIZE_HUMAN=$(
        du      --apparent-size     \
                --block-size=1      \
                --human-readable    \
                "$BACKUP"           |
        awk     '{print $1}'
        )

    BACKUPSIZE_MACHINE=$(
        du      --apparent-size     \
                --block-size=1      \
                "$BACKUP"           |
        awk     '{print $1}'
        )
}

zet_backup_terug() {
    set +o errexit
    if $OPTION_GUI; then
        (
        pv  --size="$BACKUPSIZE_MACHINE"            \
            --numeric                               \
            < "$BACKUP"                             |
        tar --extract                               \
            --directory="$TARGET"                   \
            --exclude-from="$EXCLUDEFILE_DEFAULT"   \
            --exclude-from="$EXCLUDEFILE_OPTIONAL"  \
            --file=-                                \
            "${SELECTION[@]}"                       \
            2> /dev/null
        )   2>&1                                    |
        zenity  --progress                          \
                --width=600                         \
                --height=50                         \
                --title="$title"                    \
                --text="$select$text"               \
                --auto-close                        \
                --no-cancel                         \
                --time-remaining                    \
                2> /dev/null
        TAR_RC=$?
    else
        toon_tekst "$select$text ..."
        pv  --size="$BACKUPSIZE_MACHINE"            \
            < "$BACKUP"                             |
        tar --extract                               \
            --directory="$TARGET"                   \
            --exclude-from="$EXCLUDEFILE_DEFAULT"   \
            --exclude-from="$EXCLUDEFILE_OPTIONAL"  \
            --file=-                                \
            "${SELECTION[@]}"                       \
            2> /dev/null
        TAR_RC=$?
    fi
    if ! $ARGUMENT_SELECTION && [[ $TARGET = '/' ]]; then
        zet_backup_favorieten_terug
    fi
    set -o errexit
    sync
}

zet_backup_favorieten_terug() {
    local user=''

    for dir in /home/*; do
        user=$(basename "$dir")
        sudo su --login "$user"         \
                --command "gsettings set org.gnome.shell favorite-apps < \
/home/$user/.backup-gnome-favorites"    |& $LOGCMD
    done
}

term_script() {
    if [[ $TAR_RC -eq 0 ]]; then
        toon_succestekst "De back-up is teruggezet."
        quiet; exit $SUCCESS
    else
        toon_waarschuwingstekst "De back-up is niet of slechts gedeeltelijk \
teruggezet."
        quiet; exit $WARNING
    fi
}

verwerk_script() {
    controleer_invoer "$@"
    verwerk_invoer
}

# ##############################################################################
# Hoofdlijn
# ##############################################################################
main() {
    init_script
    verwerk_script "$@"
    term_script
}

main "$@"

# Einde script
