- hosts: webservers
  become: true

  tasks:
    - name: Install Apache 2
      package: 
        name: apache2
        state: present

    - name: Start the Apache2 Webserver
      service: 
        name: apache2
        state: started
  

- hosts: dbservers
  become: true

  tasks:
    - name: Install MySQL / MariaDB
      package: 
        name:  mariadb-server
        state: present